version: '3'

services:
  my_app:
    image: my_gunicorn:latest
    build:
      context: .
      dockerfile: Dockerfile.gunicorn
      args:
        app_dir: ${CONTAINER_APP_DIR}
        secret_dir: ${CONTAINER_SECRET_DIR}
    restart: always
    volumes:
      - ${DEV_SERVER_SECRET_DIR}:${CONTAINER_SECRET_DIR}
  
  my_nginx:
    image: my_nginx:latest
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - 80:80

